[package]
name = "serverless_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
daggy = "0.8.0"
serde = "1.0.178"
lazy_static = "1.4.0"